### ISSUE TITLE
Getting a chrome driver error with v0.2.12

### ISSUE THREAD

**Issue by GrizboFen** [smkent/safeway-coupons#115]
Here's a log, let me know if there's anything else I can provide.  I installed with pip.

Error: Authentication Failure ([TimeoutException] Message:
)
<<<<<<
Traceback (most recent call last):
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\session.py", line 70, in _chrome_driver
    yield driver
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\session.py", line 153, in _login
    wait.until(self._sign_in_success)
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\session.py", line 58, in __init__
    self._login(account)
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\session.py", line 95, in _login
    with self._chrome_driver() as driver:
  File "C:\Users\osbor\scoop\apps\python\current\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\session.py", line 78, in _chrome_driver
    raise ExceptionWithAttachments(
safeway_coupons.session.ExceptionWithAttachments: [TimeoutException] Message:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\osbor\scoop\apps\python\current\Scripts\safeway-coupons.exe\__main__.py", line 7, in <module>
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\app.py", line 125, in main
    sc.clip_for_account(account)
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\safeway.py", line 38, in clip_for_account
    swy = SafewayClient(account, self.debug_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\client.py", line 17, in __init__
    self.session = LoginSession(account, debug_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\safeway_coupons\session.py", line 60, in __init__
    raise AuthenticationFailure(
safeway_coupons.errors.AuthenticationFailure: Authentication Failure ([TimeoutException] Message:
)
Exception ignored in: <function Chrome.__del__ at 0x000002497B5607C0>
Traceback (most recent call last):
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\osbor\scoop\apps\python\current\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid

**Comment by smkent** [comment]
I've updated the login flow in #130 and published a new package version (0.3.0). Please let me know if you still encounter any issues!
