### ISSUE TITLE
Think Safeway changed their UI for Login...

### ISSUE THREAD

**Issue by causefx** [smkent/safeway-coupons#120]
Timeouts due to element not existing...

**Comment by brandoncasaba** [comment]
It would appear so, see my pull req here: https://github.com/smkent/safeway-coupons/pull/119

**Comment by JerboaGobi** [comment]
> It would appear so, see my pull req here: #119

Tested with your changes and can confirm this pull req resolves the issue.

**Comment by mrlemongrass** [comment]
where in the docker image is the session.py located?

**Comment by brandoncasaba** [comment]
It gets built and installed with all dependencies with pip and deleted during image creation, see [the Dockerfile](https://github.com/smkent/safeway-coupons/blob/33909d05ef1030551bc9e70af19f5221e60d6f89/Dockerfile#L31). I recommend just rebuilding the docker image, but I suppose you could copy in the safeway_coupons folder and rerun the pip line from the Dockerfile.

**Comment by mrlemongrass** [comment]
nevermind, found it in /usr/local/lib/python3.12/site-packages/safeway_coupons/session.py

**Comment by brandoncasaba** [comment]
If you want to just directly edit the installed python package, that probably works just fine too.

**Comment by adrianbn** [comment]
@brandoncasaba even when using your code I am getting
```
Error: Authentication Failure ([TimeoutException] Message:
)
```

I received the Safeway email with the code though, so it worked fine up until that point. Not sure what is causing the timeout:

```
Traceback (most recent call last):
  File "/usr/local/bin/safeway-coupons", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/app.py", line 125, in main
    sc.clip_for_account(account)
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/safeway.py", line 38, in clip_for_account
    swy = SafewayClient(account, self.debug_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/client.py", line 17, in __init__
    self.session = LoginSession(account, debug_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 60, in __init__
    raise AuthenticationFailure(
safeway_coupons.errors.AuthenticationFailure: Authentication Failure ([TimeoutException] Message:
)
```

Any ideas?

**Comment by brandoncasaba** [comment]
Did it send you a screenshot where it got stuck? That error doesn't really show what line it got stuck on.

**Comment by adrianbn** [comment]
> Did it send you a screenshot where it got stuck? That error doesn't really show what line it got stuck on.

Not sure, where would that screenshot be?

**Comment by brandoncasaba** [comment]
It should be attached to the error email by default

**Comment by brandoncasaba** [comment]
Also may be helpful if you manually run it and copy the console output:

```
# docker ps
CONTAINER ID   IMAGE                                       COMMAND                  CREATED      STATUS      PORTS     NAMES
e1a118b585d5   localsafeway:latest                         "/usr/bin/tini -- /e…"   3 days ago   Up 3 days             safeway_safeway-coupons_1

# docker exec -it safeway_safeway-coupons_1 /bin/bash

root@e1a118b585d5:/# safeway-coupons  --accounts-config "/accounts_file" -d
Clipping coupons for Safeway account *********
Connect to safeway.com
Decline cookie prompt
Return to safeway.com after declining cookie prompt
Open Sign In sidebar
Open Sign In form
Populate Sign In form username
Click Continue button
Click Use password
Click Sign In button
Wait for signed in landing page to load
Retrieve session information
Nothing to do

```

**Comment by adrianbn** [comment]
@brandoncasaba whatever was going on with the connections the other night it has worked fine now. I am not sure why it got stuck multiple times, but it clipped the 400+ coupons this time around. I didn't get any email since I hadn't configured that setting before (I have now). If it happens again I will collect the info you asked.

**Comment by jonkudla** [comment]
Safeway.com login has reverted back it's previous sign in flow - back from the flow that pull # [119](https://github.com/smkent/safeway-coupons/pull/119) addressed (where the interface gave the user the option to receive a sign-in code or to use a password for login.

My safeway-coupon install based on [v0.2.12](https://github.com/smkent/safeway-coupons/releases/tag/v0.2.12) now works fine.

**Comment by tuxthepenguin84** [comment]
It's working again for me now on v0.2.12.
https://github.com/smkent/safeway-coupons/issues/116#issuecomment-2028780593

**Comment by jvasa** [comment]
I am seeing an error again, I wonder if things were changed again.

`Clipping coupons for Safeway account xxx@xxx.com
Connect to safeway.com
Decline cookie prompt
Return to safeway.com after declining cookie prompt
Open Sign In sidebar
Open Sign In form
Error: Authentication Failure ([TimeoutException] Message: 
)`

**Comment by jvasa** [comment]
Thanks so much, it works well, I commit this update to my image so it has the latest updates. Thanks for your hard work.

In case you are using docker-compose, I added a second cronjob that keeps the image stays up to date so especially when chrome gets updated, this continues to work:

```
version: "3.7"

services:
  safeway-coupons:
    #image: ghcr.io/smkent/safeway-coupons:latest
    image: safeway-coupons:latest
    entrypoint: >
      bash -c "
      apt update &&
      apt upgrade -y &&
      mkdir -vp /var/local/cron/crontabs &&
      install -m 755 <(echo '0 2 * * * apt update && apt upgrade -y >/proc/1/fd/1 2>/proc/1/fd/2') /var/local/cron/crontabs/root &&
      busybox crontab -l -c /var/local/cron/crontabs &&
      busybox crond -c /var/local/cron/crontabs &&
      /entrypoint"
    container_name: safeway-coupons
    network_mode: host
    environment:
      CRON_SCHEDULE: "20 3,15 * * *"
      SMTPHOST: 127.0.0.1
      SAFEWAY_ACCOUNT_USERNAME: xxx@xxx.com
      SAFEWAY_ACCOUNT_PASSWORD: xxx
      SAFEWAY_ACCOUNT_MAIL_FROM: xxx@xxx.com
      SAFEWAY_ACCOUNT_MAIL_TO: xxx@xxx.com
    restart: unless-stopped
```

**Comment by jvasa** [comment]
Looks like they made another update. There are 2 pages for login now, first page is for email, and second page is for password.

Error getting is:
`
safeway_coupons.errors.AuthenticationFailure: Authentication Failure ([NoSuchElementException] Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="label-email"]"}
  (Session info: chrome=130.0.6723.116); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception`

**Comment by brandoncasaba** [comment]
Yep, that's what they did for their other flow on the homepage. It's very similar to the login page they tried a couple months ago and abandoned. At least this one has a "use a password" button that lets you do that without getting an email/text every time you sign in. I'll make a quick change to support it. I guess I'll just do it if/else style and support both flows for now...

**Comment by jvasa** [comment]
Change works great, thank you for the quick fix. Logic in your code looks good. Here's my output:

```
Clipping coupons for Safeway account xxx@xxx.com
Connect to safeway.com/account/sign-in.html
Decline cookie prompt
Return to safeway.com after declining cookie prompt
Populate Sign In form
Click Sign in with password button
Populate password
Click Sign In button
Wait for signed in landing page to load
Retrieve session information
(1/5)  Clipped Offer SC 79456403: [Earn 8X Points*] Carl's JR Gift Cards!
(2/5)  Clipped Offer MF 53323897: [$20.00 REBATE via PayPal] DOS EQUIS® or HEINEKEN®
(3/5)  Clipped Offer SC 99958632: [$1.77 each] Pringles Chips
(4/5)  Clipped Offer SC 51518752: [$2.97 each] Signature RESERVE European Cookie Collection
(5/5)  Clipped Offer SC 99601529: [$1.97 each] Keebler Sandwich Crackers
Clipped 5 coupons
Sending email to xxx@xxx.com
>>>>>>
Safeway account: xxx@xxx.com
Clipped 5 total:
    StoreCoupon: 4 coupons
    ManufacturerCoupon: 1 coupons
<<<<<<
```

**Comment by brandoncasaba** [comment]
Make sure you do an apt "update && apt upgrade -y", seems like this issue https://github.com/smkent/safeway-coupons/issues/116

**Comment by a1ch3mist** [comment]
On Windows. Chrome update through browser seems to get through that first error (which was more explicitly logged for reason in the smkent), leading to next error. I was hoping to just swap to your repo instead of smkent which I had working before the UI change.

Error: Authentication Failure ([TimeoutException] Message: 
)
Exception ignored in: <function Popen.__del__ at 0x0000018E686E5440>
Traceback (most recent call last):
  File "C:\python3.12\Lib\subprocess.py", line 1130, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\python3.12\Lib\subprocess.py", line 1575, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

**Comment by brandoncasaba** [comment]
Those errors imply something going wrong at setup, it looks like you're getting past the driver instantiation at least now. Nothing in my branch would have changed any of that code. My branch only changes a handful of lines in the session.py file for the login flow. I'm not sure other than making sure all the dependencies are working correctly. Make sure you can still run the smkent version, my guess is you'll see the same error. You can still give the Docker version a go and just change the entrypoint file to change the command that gets set in the cronjob to load from your config or set whatever args you want to set.

**Comment by a1ch3mist** [comment]
@brandoncasaba if switching to your repo and using the docker-compose, do we switch the image name to yours?
ghcr.io/brandoncasaba/safeway-coupons:latest

I'm getting an error on that too. Otherwise, how do I incorporate your repo in the docker build of smkent? (707MB pull lol)

**Comment by brandoncasaba** [comment]
You'll have to build it manually. You can change that image: line to:
```build: https://github.com/brandoncasaba/safeway-coupons#main```

(or git pull it and make any modifications and do a ```build: ./local/path/to/safeway-coupons```)

Or you can do a ```docker build -t localsafeway:latest https://github.com/brandoncasaba/safeway-coupons#main``` where localsafeway:latest is the image:tag name you want to assign it. You'll then see it in ```docker image ls``` as a local image you can run.

**Comment by smkent** [comment]
Hi folks! Thank you all for the bug report and all of the information, and apologies for my delay in working on this. I've updated the authentication flow in #130 which should fix the Safeway login flow. Please let me know if you encounter any new issues.

**Comment by tuxthepenguin84** [comment]
Got the latest release from today and everything is working again for me, much appreciated thanks.

**Comment by jvasa** [comment]
It didn't work for me with `latest` tag, I reverted back. I had to do an apt upgrade / apt update .

Log:
```
Clipping coupons for Safeway account xxx@xxx.com
Connect to safeway.com
Decline cookie prompt
Return to safeway.com after declining cookie prompt
Open Sign In sidebar
Open Sign In form
Sending email to xxx@xxx.com
>>>>>>
Safeway account: xxx@xxx.com
Error: Authentication Failure ([TimeoutException] Message: 
)
<<<<<<
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 70, in _chrome_driver
    yield driver
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 123, in _login
    wait.until(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 58, in __init__
    self._login(account)
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 95, in _login
    with self._chrome_driver() as driver:
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 78, in _chrome_driver
    raise ExceptionWithAttachments(
safeway_coupons.session.ExceptionWithAttachments: [TimeoutException] Message: 


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/safeway-coupons", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/app.py", line 125, in main
    sc.clip_for_account(account)
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/safeway.py", line 38, in clip_for_account
    swy = SafewayClient(account, self.debug_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/client.py", line 17, in __init__
    self.session = LoginSession(account, debug_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safeway_coupons/session.py", line 60, in __init__
    raise AuthenticationFailure(
safeway_coupons.errors.AuthenticationFailure: Authentication Failure ([TimeoutException] Message: 
) 
```
