### ISSUE TITLE
Error after 1st account clipped

### ISSUE THREAD

**Issue by a1ch3mist** [smkent/safeway-coupons#124]
Running with multiple accounts. First account runs fine, but then this error occurs. Perhaps a case of how to handle teardown and setup of next session?

Clipped 471 coupons
Error: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Chrome.__del__ at 0x00000297C18F0E00>
Traceback (most recent call last):
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
    self.quit()
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid

**Comment by a1ch3mist** [comment]
Researching this, it is a Windows uc issue, with this workaround:

After installing all the items for this safeway-coupons, edit your .venv/lib for uc

In that package, edit file __init__.py

Delete/comment out this line:
time.sleep(0.1)

**Comment by smkent** [comment]
It sounds like this would be great to report to the undetected-chromedriver project, if you haven't already. I'm going to close this issue as there's no action needed in safeway-coupons.
