### ISSUE TITLE
TimeoutException running script today?

### ISSUE THREAD

**Issue by a1ch3mist** [smkent/safeway-coupons#126]
Getting this multiple times. Logging in through browser is fine:

Clipping coupons for Safeway account XXXX
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
Connect to safeway.com
Decline cookie prompt
Return to safeway.com after declining cookie prompt
Open Sign In sidebar
Open Sign In form
Traceback (most recent call last):
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\session.py", line 70, in _chrome_driver
    yield driver
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\session.py", line 123, in _login
    wait.until(
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\session.py", line 58, in __init__
    self._login(account)
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\session.py", line 95, in _login
    with self._chrome_driver() as driver:
  File "C:\python3.12\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\session.py", line 78, in _chrome_driver
    raise ExceptionWithAttachments(
safeway_coupons.session.ExceptionWithAttachments: [TimeoutException] Message:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\app.py", line 125, in main
    sc.clip_for_account(account)
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\safeway.py", line 38, in clip_for_account
    swy = SafewayClient(account, self.debug_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\client.py", line 17, in __init__
    self.session = LoginSession(account, debug_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\safeway-coupons-smkent\safeway-coupons\.venv\Lib\site-packages\safeway_coupons\session.py", line 60, in __init__
    raise AuthenticationFailure(
safeway_coupons.errors.AuthenticationFailure: Authentication Failure ([TimeoutException] Message:
)

**Comment by jvasa** [comment]
See fix at https://github.com/smkent/safeway-coupons/issues/120#issuecomment-2448168827

**Comment by smkent** [comment]
I updated the login flow in #130. Please let me know if you still encounter any issues!
