### ISSUE TITLE
Exception clipping coupons: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zhamoytin** [smkent/safeway-coupons#7]
Hello smkent,
Can you please help me to understand why on my wife's safeway account I have below error when everything works perfect for my account.

sam@ubuntu:/tmp$ ./safeway-coupons.py -c conf.ini -d
Logging in as xxxxx@hotmail.com
Retrieving CD coupons
Sending email to xxxxx@hotmail.com
>>>>>>
Safeway account: xxxxx@hotmail.com
Exception clipping coupons: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./safeway-coupons.py", line 278, in _clip_coupons
    offers = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

<<<<<<
sam@ubuntu:/tmp$

**Comment by zhamoytin** [comment]
Looks like issue is gone after after she made couple purchases on this new safeway account. Closing the issue.
