### ISSUE TITLE
Chrome driver issue?

### ISSUE THREAD

**Issue by causefx** [smkent/safeway-coupons#94]
Getting `Status code was: -5` on latest update

Any other info I can grab you?
```
root@1de05ad89bf2:/# safeway-coupons --no-email -d
Clipping coupons for Safeway account email@me.com
Would send email to email@me.com
>>>>>>
Safeway account: email@me.com
Error: Authentication Failure (Message: Service /root/.local/share/undetected_chromedriver/undetected_chromedriver unexpectedly exited. Status code was: -5
)
<<<<<<
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/session.py", line 56, in __init__
    self._login(account)
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/session.py", line 89, in _login
    with uc.Chrome(options=options) as driver:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 97, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /root/.local/share/undetected_chromedriver/undetected_chromedriver unexpectedly exited. Status code was: -5


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/safeway-coupons", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/app.py", line 125, in main
    sc.clip_for_account(account)
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/safeway.py", line 38, in clip_for_account
    swy = SafewayClient(account, self.debug_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/client.py", line 17, in __init__
    self.session = LoginSession(account, debug_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/safeway_coupons/session.py", line 62, in __init__
    raise AuthenticationFailure(e, account) from e
safeway_coupons.errors.AuthenticationFailure: Authentication Failure (Message: Service /root/.local/share/undetected_chromedriver/undetected_chromedriver unexpectedly exited. Status code was: -5
)
```

**Comment by smkent** [comment]
Hi, I've just released version 0.2.7 which uses Chrome 119. Please let me know if you run into any errors with the newest version.
